import { readFileSync, writeFileSync } from "node:fs"

const set = JSON.parse(readFileSync("./node_modules/@iconify-json/ph/icons.json", "utf8"))

const wanted = [
    "speaker-high", "speaker-slash", "headphones", "eye", "users",
    "caret-left", "caret-right", "caret-down",
    "arrows-out", "arrows-in", "crosshair", "star-fill", "arrow-counter-clockwise",
    "warning-circle", "record-fill", "map-trifold", "faders", "info",
    "video-camera", "video-camera-slash", "wifi-slash", "microphone", "circle-notch"
]

const missing = wanted.filter(n => !set.icons[n])
if (missing.length) throw new Error("missing icons: " + missing.join(", "))

const entries = wanted
    .map(n => `    "${n}": ${JSON.stringify(set.icons[n].body)}`)
    .join(",\n")

writeFileSync("./src/assets/icons.ts", `/*
 * Inline Phosphor icon paths, generated by scripts/icons.mjs (pnpm icons) from
 * @iconify-json/ph. Inline <svg> inherits currentColor and costs only the
 * glyphs the UI uses. Do not edit by hand: add a name to the script instead.
 */

export const VIEW_BOX = "0 0 ${set.width ?? 256} ${set.height ?? 256}"

export const icons = {
${entries}
} as const

export type IconName = keyof typeof icons
`)

console.log("wrote src/assets/icons.ts with", wanted.length, "icons")
